name: Build and deploy a new release

on:
  push:
    branches: ["master"]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Package
      run: npm run dist:linux

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Package
      env:
        CSC_LINK: ${{ secrets.CSC_LINK }}
      run: npm run dist:mac
  
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Package
      env:
        CSC_LINK: ${{ secrets.CSC_LINK }}
      run: npm run dist:win